### ISSUE TITLE
Feature request:  Minidump support

### ISSUE THREAD

**Issue by DigiAngel** [blackberry/pe_tree#7]
It's a rare day I actually need to dump the entire system memory.  But process dumps via procdump or similar I use all the time...any chance we could get support for a minidump file?  Thank you.

**Comment by tombonner** [comment]
Hi @DigiAngel,

I shall certainly give the idea strong consideration, as I often rely on minidumps myself. There appears to be a library for processing minidump files under python (https://github.com/skelsec/minidump/tree/master/minidump), so hopefully it would be fairly trivial to implement.

In the meantime, if you have Rekall installed, it is possible to dump processes/modules/drivers on a live system without the need for a full memory dump...

```
$ rekall --live Memory
[1] Live (Memory) 00:00:00> run -i pe_tree_rekall.py
```

From there, you can dump the PE's you are interested in (right click -> dump) and select "Rebuild imports" to build a new IAT...

![image](https://user-images.githubusercontent.com/1394319/95064951-5012d680-06f8-11eb-99af-e79f13456bea.png)

Thanks,

Tom

**Comment by tombonner** [comment]
One other approach that may work? If you have IDAPro you can open the minidump file that way and use the PE Tree IDA plugin to view/dump processes and modules.

**Comment by DigiAngel** [comment]
Thank you.  My hope has been to run and dump on a machine without IDA, then copy the procdump's over and analyze them further.  I'll try the above approach as well..thank you!
